name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      # Deploy
      - name: Deploy Exigo Dev
        uses: actions/checkout@v2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          ssh-key: |
            ${{ secrets.KEY }}
            ${{ secrets.PUB_KEY }}
          script: cd ${{ secrets.PROJECT_PATH }} && git pull && docker container ls

