name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Deploy
      - name: Deploy to Exigo Dev
        run: "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no"
        root@116.203.229.86: docker container restart odoo
