name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    if: github.ref == 'refs/heads/master'
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Push to server
          uses: maksgr/test_github_actions@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            script: cd ${{ secrets.PROJECT_PATH }} && git pull

